version: 2.1

orbs:
  cimg: circleci/cimg@0.6.4

parameters:
  trigger:
    type: boolean
    default: false

workflows:
  automated-wf:
    when: << pipeline.parameters.trigger >>
    jobs:
      - cimg/update:
          update-script: gcpFeed.sh
          context:
            - cpe-image-bot-github-creds
  main-wf:
    when:
      not: << pipeline.parameters.trigger >>
    jobs:
      - build:
          name: Test
          filters:
            branches:
              ignore:
                - main
          context: cimg-docker-image-building
      - build:
          name: Deploy
          filters:
            branches:
              only:
                - main
          context:
            - cimg-docker-image-building
            - cimg-docker-image-publishing
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: 2xlarge+
    steps:
      - checkout
      - setup_remote_docker:
          version: "docker24"
      - run:
          name: "Build Docker Images"
          command: |
            ./build-images.sh
            echo 'export DOCKER_PASS=$DOCKER_TOKEN' >> $BASH_ENV
      - deploy:
          name: "Publish Docker Images (main branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then

              echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin

              # an else block will be added in the future for a staging release
              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Publishing cimg/gcp to Docker Hub production."
                ./push-images.sh
              else
                echo "Skipping publishing."
              fi
            fi
